site_name: Modelos de documentos acadêmicos
site_description: Este projeto busca fornecer modelos para projetos acadêmicos.
repo_url: https://github.com/ValerioMedeiros/Modelos_de_documentos
edit_uri: edit/main/docs/

copyright: Este projeto é distribuído sobre licença acadêmica livre (MIT).

theme:
  name: material
  language: pt

plugins:
  - search
  - mermaid2
extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js